project_id = "kqiqotbhynmifrphcnqu"

[functions.test-api-profile]
verify_jwt = true

[functions.create-test-run]
verify_jwt = true

[functions.start-sms-test-run]
verify_jwt = true

[functions.stop-sms-test-run]
verify_jwt = true

[functions.check-dlr-status]
verify_jwt = true

[functions.run-sender-experiment]
verify_jwt = true

[functions.test-raw-template]
verify_jwt = true

[functions.create-load-runner-job]
verify_jwt = true

[functions.stop-load-runner-job]
verify_jwt = true

[functions.pause-load-runner-job]
verify_jwt = true

[functions.resume-load-runner-job]
verify_jwt = true

[functions.get-load-runner-job-status]
verify_jwt = true

